if [ -z $1 ]; then
  echo "Version Number not defined for PrjFSVersion.h"
fi

# Generate PrjFSVersion.h
SCRIPTDIR=$(dirname ${BASH_SOURCE[0]})
cat >$SCRIPTDIR/../../../BuildOutput/PrjFSVersion.h <<TEMPLATE
// This header file was generated by GeneratePrjFSVersionHeader.sh

#define PrjFSVersionString "$1"
TEMPLATE
